---
title: "Appendix"
author: "Yunran Chen"
date: "2017/12/11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE, warning=FALSE, paged.print=FALSE}
library(tibble)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(stringr)
library(BAS)
library("R2jags")

bioassay.read = read.table("http://stat.duke.edu/sites/stat.duke.edu/files/bioassay.txt",
                       header=T,stringsAsFactors = FALSE) %>% as.tibble()

bioassay=bind_cols(map_df(bioassay.read %>% select(uterus,weight,EE,ZM),~.x %>% as.numeric(.)),
                   map_df(bioassay.read %>% select(protocol,lab,group),~.x %>% as.factor(.))
                   ) %>% as.tibble()
bioassay.fac=bioassay %>% mutate(EE=as.factor(EE),ZM=as.factor(ZM))
```

### Part I

#### summary

```{r summary,  message=FALSE, warning=FALSE, paged.print=FALSE}
##1)We can consider `weight` and `uterus` as continuous variable. All other variables only have seperate values.
summary(bioassay)
bioassay %>% select(EE) %>% table()
bioassay %>% select(ZM) %>% table()
##2)There are significant interaction among variables. Because each labs adopted differet treatment.
table(bioassay$EE,bioassay.fac$lab)
##visualization for points
#ggplot(data=bioassay,mapping = aes(y = lab,x = protocol,color=as.factor(ZM)))+
#  geom_jitter(alpha=0.5)
#ggplot(data=bioassay.fac,mapping = aes(y = lab,x = ZM,color=protocol))+
#  geom_jitter(alpha=0.5)
#ggplot(data=bioassay,mapping = aes(y = lab,x = protocol,color=as.factor(EE)))+
#  geom_jitter(alpha=0.5)
#ggplot(data=bioassay,mapping = aes(y = lab,x = protocol,color=as.factor(EE)))+
#     geom_count(alpha=0.5,position = "jitter")
```

#### EDA

```{r EDA, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
##---------------------boxplot
##different labs have diff mean on ZM. interaction on labs and protocol.
##when consider ZM as numeric, the diff is not sig in pic. but in factor - diff.
###4var:ZM

outliers=c(1426,926,1586)#,1425,1946,2666)
ggplot(data=bioassay.fac,mapping = aes(y = uterus,x = ZM,color=lab))+
  geom_boxplot()+theme_bw()+facet_wrap(~ protocol)+
  geom_text(data=bioassay.fac[outliers,],
            aes(label=outliers,color=lab))
#+theme(legend.position="bottom",
#       legend.title=element_blank())
##caculate the mean for different group 
#bioassay.fac %>% group_by(ZM) %>% summarize(mean=mean(uterus,na.rm=T))

##4var:EE
ggplot(data=bioassay.fac,mapping = aes(y = uterus,x = EE,color=lab))+
  geom_boxplot()+theme_bw()+facet_wrap(~ protocol)+
  geom_text(data=bioassay.fac[outliers,],
            aes(label=outliers,color=lab))
#+scale_colour_discrete(guide = FALSE)
##caculate the mean for different group.
#bioassay.fac %>% group_by(EE) %>% summarize(mean=mean(uterus,na.rm=T))

##weights
ggplot(data=bioassay.fac,mapping = aes(y = uterus,x = weight))+
  geom_point()+geom_smooth(method = "lm")+theme_bw()+facet_wrap(~ protocol,scales = "free")+
  geom_text(data=bioassay.fac[outliers,],
            aes(label=outliers,color=lab))

```

####Model and Results(Explaination are all inside the chunck)

```{r lm.full.fac, message=FALSE, warning=FALSE, paged.print=FALSE}
lm.full.fac=lm(data = bioassay.fac[-c(1586,926),],formula = uterus~EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab) 

#plot(lm.full.fac) ##use the plot to check model assumption. (detect outliers, normality, influential points.)

#bioassay.fac %>% select(EE,ZM) %>% table() -- there is imbalanced distribution 

#summary(lm.full.fac)
#Adjusted R-squared:  0.9538 

##if consider EE,ZM as numeric
#lm.full.q=lm(data = bioassay,formula = #uterus~poly(EE,2)+poly(ZM,2)+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab)
#anova(lm.full.q)
#summary(lm.full.q) #0.8286 #p=69 
```

```{r functions,  message=FALSE, warning=FALSE, paged.print=FALSE}
eff.tbl=function(lm.obj){
  
  ind.mat=matrix(0,nrow=nrow(summary(lm.obj)$coefficients),ncol=7)
  colnames(ind.mat)=c("EE","ZM","lab","protocol","EEdose","ZMdose","interaction")
  ind.mat=cbind(coef=summary(lm.obj)$coefficients%>%rownames(.),ind.mat)
  ind.mat[str_detect(ind.mat[,1],"EE"),"EE"]=1
  ind.mat[str_detect(ind.mat[,1],"ZM"),"ZM"]=1
  ind.mat[str_detect(ind.mat[,1],"lab"),"interaction"]=1
  ind.mat[str_detect(ind.mat[,1],"protocol"),"interaction"]=1
  
  for (dose in c(bioassay.fac$EE %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("EE",dose)),"EEdose"]=dose
  }
  for (dose in c(bioassay.fac$ZM %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("ZM",dose)),"ZMdose"]=dose
  }
  for (lab in c(bioassay.fac$lab %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("lab",lab)),"lab"]=lab
  }     
  for (protocol in c(bioassay.fac$protocol %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("protocol",protocol)),"protocol"]=protocol
  }  
  ind.tbl=ind.mat%>% as.tibble()
  return(ind.tbl)
}

t.test=function(lm.obj,str.ee,str.lab,str.ori){
ind.tbl=eff.tbl(lm.obj)
cov.coef=vcov(lm.obj)
p=nrow(ind.tbl)
i.levels=bioassay.fac %>% pull(str.ori) %>% levels() #original colnames in bioassay.fac
i.n=i.levels %>% length(.)
lambda=matrix(nrow=i.n,ncol=nrow(ind.tbl))
lab.ee=t.value=p.value=denominator=nominator=numeric(i.n)

for (i in 1:i.n){
  lambda[i,]=((ind.tbl[str.lab]==i.levels[i])&(ind.tbl[str.ee]=="1"))|((ind.tbl[str.ee]=="1")&(ind.tbl["interaction"]=="0"))
  lab.ee[i]=summary(lm.obj)$coefficients[lambda[i,],"Estimate"] %>% sum()
  denominator[i]=(cov.coef[lambda[i,],lambda[i,]]) %>% sum() %>% sqrt() 
  nominator[i]=lab.ee[i] %>% abs()
  t.value[i]=(nominator[i])/(denominator[i])
  p.value[i]=pt(q = t.value[i],df = summary(lm.obj)$df[2],lower.tail = FALSE)
}

res=list(t.test=tibble(i.levels,p.value,estimator=lab.ee),value=tibble(i.levels,variance=denominator,estimator=nominator))
return(res)
}
```

```{r part1.result, warning=FALSE, paged.print=FALSE}
#0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

##a.1
##uterotrophic bioassay successful overal at identifying effects of EE and ZM. F-test for EE,ZM are significant. For the significant coefficients, all EE are positive, ZM are negative. 
anova(lm.full.fac)

coefs=rownames(summary(lm.full.fac)$coefficients)

res=summary(lm.full.fac)$coefficients %>%
  cbind(coef=coefs,.) %>% 
  as.tibble() #get the coefficients matrix

colnames(res)=c("coef","estimate","std_error","t_value","p_value")

res %>% filter(as.numeric(p_value)<0.05) %>% slice(1:10)


##a.2 do some labs fail t detect such effects
##There are some labs fail to detect such effects, as follows:"Huntingd""Bayer""ChungKor""TNO""Zeneca"  
a.2.ee=t.test(lm.full.fac,"EE","lab","lab")$t.test
a.2.ee
a.2.ee %>% filter(((p.value<0.05)&(estimator<0))|(p.value>0.05))# %>% pull(i.levels)

a.2.zm=t.test(lm.full.fac,"ZM","lab","lab")$t.test
a.2.zm
a.2.zm %>% filter(((p.value<0.05)&(estimator>0))|(p.value>0.05))#%>% pull(i.levels)

##a.3 the change dose for EE? vary across labs?
##From the output of summary. The change dose for EE is EE3. Dose larger than this is significant, less than this is not significant. The value varies across labs. Because for different labs, the dose changing points is different. For example, SUmitomo. EE0.3 may be the changing dose point. For Huntingd, EE0.1 may be the changing dose point.

##b. does the dose reponse vary across labs? are there certain labs stands out as being different?
##From the output of summary. There exist several significant interaction cofficients, meaning dose reponse vary across labs. The labs Berlin and Sumitomo stands out as being different.(with pvalue<0.001 for EE:labs). The labs Bayer,Poulenc,Zeneca stands out as being different.(with pvalue<0.005 for ZM:labs)

res %>% filter(str_detect(res$coef,"EE.*lab")) %>%
  filter(p_value<0.001)

res %>% filter(str_detect(res$coef,"ZM.*lab")) %>%
  filter(p_value<0.005)

##c.Do the protocols differ in sensitivity to detect? Which one recommend?
##From the result from anova. The protocols differ. And the variance of protocol C,D is super large. Protocol A and B would be recommended.

anova(lm.full.fac)["EE:protocol", ]
anova(lm.full.fac)["ZM:protocol", ]

res %>% filter(str_detect(res$coef,"^protocol"))

res %>% filter(str_detect(res$coef,"EE.*protocol")) 

res %>% filter(str_detect(res$coef,"ZM.*protocol"))

```

### Part II

```{r bays.fac.1.gprior}
#EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab
n=nrow(bioassay.fac)
X.fac.1=model.matrix(data=bioassay.fac,object =~ EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab)
p=ncol(X.fac.1)-1
bas.fac.1=bas.lm(formula =uterus~EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab,
                 data=bioassay.fac,
                 prior="g-prior",
                 alpha=n,
                 #n.models=20000,
                 method = "MCMC",
                 thin=10,
                 #initprobs = "eplogp",
                 MCMC.iterations = 500000)
bas.fac.1
image(bas.fac.1)
plot(bas.fac.1)
#summary(bas.fac.1)
coef(bas.fac.1) %>% plot(.,ask=F)
##diagonose
diagnostics(bas.fac.1,"pip")
#cv.summary.bas()
```


###Part III


Prepare the data

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

# Create a data list with inputs for JAGS

X.fac=model.matrix(data=bioassay,object =~EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab)[,-1]
n=nrow(bioassay)
## scale X such that X^TX has ones on the diagonal;
## scale divides by the standard deviation so we need
## to divide by the sqrt(n-1)
scaled.X = scale(X.fac)/sqrt(n-1)
# are diagonal elements 1?
# check
#t(scaled.X) %*% scaled.X
data = list(Y = bioassay$uterus, 
            X=scaled.X, 
            p=ncol(scaled.X),
            n = n)

#extract the scales from the scaled object and fix--add to attr
data$scales = attr(scaled.X, "scaled:scale")*sqrt(n-1) # fix scale
data$Xbar = attr(scaled.X, "scaled:center")

```

Jags code

```{r jags, eval=FALSE}
##For jags: need to use <-; use precision instead of sigma_sq
rr.model = function() {
  a <- 2
  shape<-a/2

  for (i in 1:n) {
    mu[i] <- alpha0 + inprod(X[i,], alpha)
    prec[i] <- phi
    Y[i] ~ dnorm(mu[i], prec[i])
  }
  phi ~ dgamma(1.0E-6, 1.0E-6)  ##jags do not allow improper prior
  alpha0 ~ dnorm(0, 1.0E-6) 

  for (j in 1:p) {
    phi.l[j] <- pow(i.phi.l[j], -2)    
    prec.beta[j] <- lambda.l[j]*phi*phi.l[j]
    alpha[j] ~ dnorm(0, prec.beta[j])
    # transform back to original coefficients
    beta[j] <- alpha[j]/scales[j]
    lambda.l[j] ~ dgamma(shape, shape)
    i.phi.l[j] ~ dt(0,1,1)%_%T(0,)

  }

  # transform intercept to usual parameterization 
  beta0 <- alpha0 - inprod(beta[1:p], Xbar)

  sigma <- pow(phi, -.5)
}

# parameters to monitor
parameters = c("beta0", "beta", "sigma","lambda.l", "phi.l")

# run jags from R  (see Resources to install)
stack.sim.hfac = jags(data, 
                 inits=NULL, 
                 par=parameters,
                 model=rr.model, 
                 n.iter=30000)
saveRDS(stack.sim.hfac, "stack.sim.rds")
stack.sim=readRDS("stack.sim.rds")
```

Load the data I stored.

```{r load.data}

```

Analysis on simulation result.


```{r}
# create an MCMC object with the results for the MCMC draws
stack.mcmc = as.mcmc(stack.sim$BUGSoutput$sims.matrix)  #get the simulation points

```

