---
title: "Project"
author: "Yunran Chen"
date: "2017/12/8"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(tibble)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(stringr)

bioassay.read = read.table("http://stat.duke.edu/sites/stat.duke.edu/files/bioassay.txt",
                       header=T,stringsAsFactors = FALSE) %>% as.tibble()

bioassay=bind_cols(map_df(bioassay.read %>% select(uterus,weight,EE,ZM),~.x %>% as.numeric(.)),
                   map_df(bioassay.read %>% select(protocol,lab,group),~.x %>% as.factor(.))
                   ) %>% as.tibble()
bioassay.fac=bioassay %>% mutate(EE=as.factor(EE),ZM=as.factor(ZM))
```

```{r EDA}
##Protocol: For EE, AB no interaction. CD small interaction. AB and CD are different! (immature--adult)
##But for ZZ, AB CD interaction. AB CD are different!
##consider take apart the `protocol` into 2 parts.


##protocol+labs+ZM(inter(labs,ZM);inter(protocol,ZM);)

##---------------------points+lm
###3variable
ggplot(data=bioassay,mapping = aes(y = uterus,x = ZM,color=protocol))+
  geom_point()+geom_smooth(method = "lm")+theme_bw()
###4var
ggplot(data=bioassay,mapping = aes(y = uterus,x = ZM,color=lab,alpha=0.1))+
  geom_point()+geom_smooth(method = "lm",se=FALSE)+theme_bw()+facet_wrap(~ protocol)

##---------------------boxplot
##different labs have diff mean on ZM. interaction on labs and protocol.
##when consider ZM as numeric, the diff is not sig in pic. but in factor - diff.
###4var
ggplot(data=bioassay,mapping = aes(y = uterus,x = as.factor(ZM),color=lab))+
  geom_boxplot()+theme_bw()+facet_wrap(~ protocol)

##3var:protocol
ggplot(data=bioassay,mapping = aes(y = uterus,x = EE,color=protocol))+
  geom_point()+geom_smooth(method = "lm")+theme_bw()


##protocol:lab
ggplot(data=bioassay,mapping = aes(y = lab,x = protocol))+
  geom_jitter()

##protocol:weight
##lab:weight
##protocol:lab:weight
ggplot(data=bioassay %>% filter(protocol %in% c("A")),# c("C","D")
       mapping = aes(y = uterus,x = weight,color=lab))+
  geom_point()+geom_smooth(method = "lm",se=FALSE)+theme_bw()

##group:protocol:x
ggplot(data=bioassay,mapping = aes(y = uterus,x = as.factor(ZM),color=protocol:group,fill=protocol))+
  geom_boxplot()+theme_bw()#+facet_wrap(~ protocol)

```


## Part I: OLS/MLE


```{r lm.full.1, echo=FALSE}
##----------------------------------------FULL

lm.full=lm(data = bioassay,formula = uterus~EE+ZM+protocol+lab+group+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab+EE:group+ZM:group+EE:protocol:lab+ZM:protocol:lab+lab:protocol+group:protocol+weight:lab)
summary(lm.full)
anova(lm.full)


```


```{r lm.full.2}
##----------------------------------------Simple
lm.full.simple=lm(data = bioassay,formula = uterus~EE+ZM+protocol+lab+group+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab)
anova(lm.full.simple)
summary(lm.full.simple)
##------Q1
ind=str_detect(summary(lm.full.simple)$coefficients %>% rownames(),"EE")
eff.coeff.2=summary(lm.full.simple)$coefficients %>%
  as.data.frame() %>% 
  mutate(coeff=rownames(.)) %>% 
  filter(ind)

```

```{r functions}
eff.tbl=function(lm.obj){
  
  ind.mat=matrix(0,nrow=nrow(summary(lm.obj)$coefficients),ncol=6)
  colnames(ind.mat)=c("EE","ZM","lab","protocol","EEdose","ZMdose")
  ind.mat=cbind(coef=summary(lm.obj)$coefficients%>%rownames(.),ind.mat)
  ind.mat[str_detect(ind.mat[,1],"EE"),"EE"]=1
  ind.mat[str_detect(ind.mat[,1],"ZM"),"ZM"]=1
  
  for (dose in c(bioassay.fac$EE %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("EE",dose)),"EEdose"]=dose
  }
  for (dose in c(bioassay.fac$ZM %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("ZM",dose)),"ZMdose"]=dose
  }
  for (lab in c(bioassay.fac$lab %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("lab",lab)),"lab"]=lab
  }     
  for (protocol in c(bioassay.fac$protocol %>% levels())){
     ind.mat[str_detect(ind.mat[,1],paste0("protocol",protocol)),"protocol"]=protocol
  }  
  ind.tbl=ind.mat%>% as.tibble()
  return(ind.tbl)
}

```



```{r lm.full.fac.1}
##protocol seperate or not?

##consider EE ZM as factor
lm.full.fac.1=lm(data = bioassay.fac,formula = uterus~EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab+EE:protocol:lab+ZM:protocol:lab+lab:protocol) #weight:lab,
plot(lm.full.fac.1)
##---Q1:
#(1)significant in EE & ZM; 
anova(lm.full.fac.1)
#(1)EE:+;ZM:-
ind.tbl=eff.tbl(lm.full.fac.1)
ind.tbl[1,]="1"
ee=summary(lm.full.fac.1)$coefficients[ind.tbl$EE=="1","Estimate"] %>% sum()
ee
zm=summary(lm.full.fac.1)$coefficients[ind.tbl$ZM=="1","Estimate"] %>% sum()
zm
#(2)some labs:
##basis:Basf
##EE:+
##ZM:-
labeff=function(str.ee,str.lab,str.ori){
ee=summary(lm.full.fac.1)$coefficients[ind.tbl[str.ee]=="1","Estimate"] %>% sum()
lab.null=summary(lm.full.fac.1)$coefficients[(ind.tbl[str.lab]=="0")&(ind.tbl[str.ee]=="1"),"Estimate"] %>% sum()
i.levels=bioassay.fac %>% pull(str.ori) %>% levels()
i.n=i.levels %>% length(.)
lab.ee=length(i.n)
for (i in 1:i.n){
  lab.ee[i]=summary(lm.full.fac.1)$coefficients[(ind.tbl[str.lab]!=i.levels[i])&(ind.tbl[str.ee]=="1"),"Estimate"] %>% sum()
}
res=ee-lab.ee+lab.null

return(tibble(i.levels,res))
}

labeff("EE","lab","lab")
labeff("ZM","lab","lab")
#(3)dose
labeff("EE","EEdose","EE") #0.1-|-0.3
labeff("ZM","ZMdose","ZM") #0-|-0.1
#b.(1)dose+lab

#b.(2)

#c.(1)protocol
labeff("EE","protocol","protocol")
labeff("ZM","protocol","protocol")
```

```{r lm.full.fac.2}
##without 3 interaction--simple
lm.full.fac.2=lm(data = bioassay.fac,formula = uterus~EE+ZM+lab+protocol+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab) 
anova(lm.full.fac.2)
plot(lm.full.fac.2)
summary(lm.full.fac.2)
```


