---
title: "Project"
author: "Yunran Chen"
date: "2017/12/8"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
library(tibble)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(stringr)

bioassay.read = read.table("http://stat.duke.edu/sites/stat.duke.edu/files/bioassay.txt",
                       header=T,stringsAsFactors = FALSE) %>% as.tibble()

bioassay=bind_cols(map_df(bioassay.read %>% select(uterus,weight,EE,ZM),~.x %>% as.numeric(.)),
                   map_df(bioassay.read %>% select(protocol,lab,group),~.x %>% as.factor(.))
                   ) %>% as.tibble()
bioassay.fac=bioassay %>% mutate(EE=as.factor(EE),ZM=as.factor(ZM))
```

```{r EDA}
##Protocol: For EE, AB no interaction. CD small interaction. AB and CD are different! (immature--adult)
##But for ZZ, AB CD interaction. AB CD are different!
##consider take apart the `protocol` into 2 parts.


##protocol+labs+ZM(inter(labs,ZM);inter(protocol,ZM);)

##---------------------points+lm
###3variable
ggplot(data=bioassay,mapping = aes(y = uterus,x = ZM,color=protocol))+
  geom_point()+geom_smooth(method = "lm")+theme_bw()
###4var
ggplot(data=bioassay,mapping = aes(y = uterus,x = ZM,color=lab,alpha=0.1))+
  geom_point()+geom_smooth(method = "lm",se=FALSE)+theme_bw()+facet_wrap(~ protocol)

##---------------------boxplot
##different labs have diff mean on ZM. interaction on labs and protocol.
##when consider ZM as numeric, the diff is not sig in pic. but in factor - diff.
###4var
ggplot(data=bioassay,mapping = aes(y = uterus,x = as.factor(ZM),color=lab))+
  geom_boxplot()+theme_bw()+facet_wrap(~ protocol)

##3var:protocol
ggplot(data=bioassay,mapping = aes(y = uterus,x = EE,color=protocol))+
  geom_point()+geom_smooth(method = "lm")+theme_bw()


##protocol:lab
ggplot(data=bioassay,mapping = aes(y = lab,x = protocol))+
  geom_jitter()

##protocol:weight
##lab:weight
##protocol:lab:weight
ggplot(data=bioassay %>% filter(protocol %in% c("A")),# c("C","D")
       mapping = aes(y = uterus,x = weight,color=lab))+
  geom_point()+geom_smooth(method = "lm",se=FALSE)+theme_bw()

##group:protocol:x
ggplot(data=bioassay,mapping = aes(y = uterus,x = as.factor(ZM),color=protocol:group,fill=protocol))+
  geom_boxplot()+theme_bw()#+facet_wrap(~ protocol)

```


## Part I: OLS/MLE


```{r lm.full.1, echo=FALSE}
##----------------------------------------FULL

lm.full=lm(data = bioassay,formula = uterus~EE+ZM+protocol+lab+group+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab+EE:group+ZM:group+EE:protocol:lab+ZM:protocol:lab+lab:protocol+group:protocol+weight:lab)
summary(lm.full)
anova(lm.full)


```


```{r lm.full.2}
##----------------------------------------Simple
lm.full.simple=lm(data = bioassay,formula = uterus~EE+ZM+protocol+lab+group+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab)
anova(lm.full.simple)
summary(lm.full.simple)
##------Q1
ind=str_detect(summary(lm.full.simple)$coefficients %>% rownames(),"EE")
eff.coeff.2=summary(lm.full.simple)$coefficients %>%
  as.data.frame() %>% 
  mutate(coeff=rownames(.)) %>% 
  filter(ind)

```

```{r lm.full.fac.1}
##protocol seperate or not?

##consider EE ZM as factor
lm.full.fac.1=lm(data = bioassay.fac,formula = uterus~EE+ZM+protocol+lab+weight+EE:protocol+ZM:protocol+EE:lab+ZM:lab+EE:protocol:lab+ZM:protocol:lab+lab:protocol+weight:lab)

##---Q1:
#(1)significant in EE & ZM; 
anova(lm.full.fac.1)
#(1)EE:+;ZM:-

eff.coef=function(lm.obj,str){
  coef=summary(lm.obj)$coefficients
  ind=str_detect( coef %>% rownames(),str)
  eff.coef=coef %>%
    as.data.frame() %>% 
    mutate(coeff=rownames(.)) %>% 
    filter(ind) %>% 
    pull(Estimate) %>% sum()+coef[1,1] #intercept
return(eff.coef)
}
eff.coef(lm.full.fac.1,"EE") #+
eff.coef(lm.full.fac.1,"ZM") #-

#(2)SOME LABS:
EE10:labPoulenc 
paste0("EE[0-9.:]+lab","abc","|","EE[0-9.]+$","|")
map_int(bioassay.read$lab,~eff.coef(lm.full.fac.1,.x) )

ind.mat=matrix(.nrow=nrow())
str_detect(.,"EE")

```



